const Product = require("../models/Product");

var productList = [
  {
    id: 1,
    category: "Laptop",
    name: "Dell Inspiron 15",
    description: "Intel i5 | 8GB RAM | 512GB SSD",
    price: 55000,
    image: "../images/laptop1.jpg",
  },
  {
    id: 2,
    category: "Mobile",
    name: "Samsung Galaxy S25",
    description: "12GB RAM | 256GB Storage",
    price: 79999,
    image: "../images/mobile1.webp",
  },
  {
    id: 3,
    category: "Book",
    name: "Java Programming",
    description: "Beginner to Advanced Guide",
    price: 699,
    image: "../images/book1.webp",
  },
  {
    id: 4,
    category: "Laptop",
    name: "HP Pavilion",
    description: "Intel i7 | 16GB RAM | 1TB SSD",
    price: 72000,
    image: "../images/laptop2.webp",
  },
  {
    id: 5,
    category: "Pen",
    name: "Cello Butterflow",
    description: "Blue Ball Pen",
    price: 20,
    image: "../images/pen1.webp",
  },
  {
    id: 6,
    category: "Mobile",
    name: "Apple iPhone 16",
    description: "128GB | A18 Chip",
    price: 89999,
    image: "../images/mobile2.webp",
  },
  {
    id: 7,
    category: "Vegetable",
    name: "Fresh Tomato",
    description: "Fresh Tomato 1kg",
    price: 40,
    image: "../images/vegetable1.jpg",
  },
  {
    id: 8,
    category: "Laptop",
    name: "Lenovo IdeaPad",
    description: "Ryzen 5 | 8GB RAM | 512GB SSD",
    price: 48000,
    image: "../images/laptop3.webp",
  },
  {
    id: 9,
    category: "Watch",
    name: "Titan Analog Watch",
    description: "Premium Leather Strap",
    price: 3500,
    image: "../images/watch1.webp",
  },
  {
    id: 10,
    category: "Mobile",
    name: "OnePlus 13",
    description: "12GB RAM | 256GB Storage",
    price: 64999,
    image: "../images/mobile3.webp",
  },
  {
    id: 11,
    category: "Flower",
    name: "Red Rose",
    description: "Fresh Rose Bouquet",
    price: 250,
    image: "../images/flower.jpg",
  },
  {
    id: 12,
    category: "Laptop",
    name: "Apple MacBook Air M2",
    description: "Apple M2 | 8GB RAM | 256GB SSD",
    price: 109999,
    image: "../images/laptop4.webp",
  },
  {
    id: 13,
    category: "Table",
    name: "Wooden Study Table",
    description: "Engineered Wood Table",
    price: 4999,
    image: "../images/table1.jpg",
  },
  {
    id: 14,
    category: "Mobile",
    name: "Realme GT 7",
    description: "8GB RAM | 256GB Storage",
    price: 35999,
    image: "../images/mobile4.jpg",
  },
  {
    id: 15,
    category: "Grocery",
    name: "Fortune Sunflower Oil",
    description: "Refined Oil 1L",
    price: 180,
    image: "../images/grocery1.jpg",
  },
  {
    id: 16,
    category: "Laptop",
    name: "ASUS VivoBook",
    description: "Intel i3 | 8GB RAM | 512GB SSD",
    price: 42000,
    image: "../images/laptop5.webp",
  },
  {
    id: 17,
    category: "Book",
    name: "Python Programming",
    description: "Complete Python Guide",
    price: 799,
    image: "../images/book2.webp",
  },
  {
    id: 18,
    category: "Mobile",
    name: "Redmi Note 14 Pro",
    description: "8GB RAM | 128GB Storage",
    price: 24999,
    image: "../images/mobile5.jpg",
  },
  {
    id: 19,
    category: "Pen",
    name: "Reynolds Trimax",
    description: "Blue Gel Pen",
    price: 45,
    image: "../images/pen2.webp",
  },
  {
    id: 20,
    category: "Flower",
    name: "White Lily",
    description: "Fresh Flower Bouquet",
    price: 300,
    image: "../images/flower2.webp",
  },
  {
    id: 21,
    category: "Pen",
    name: "Reynolds Trimax",
    description: "Blue Gel Pen",
    price: 45,
    image: "../images/pen2.webp",
  },
  {
    id: 22,
    category: "Vegetable",
    name: "Fresh Carrot",
    description: "Organic Carrot 1kg",
    price: 60,
    image: "../images/vegetable2.jpg",
  },
  {
    id: 23,
    category: "Book",
    name: "Data Structures Using Java",
    description: "Programming Concepts",
    price: 850,
    image: "../images/book3.webp",
  },
  {
    id: 24,
    category: "Mobile",
    name: "Vivo V50",
    description: "8GB RAM | 256GB Storage",
    price: 32999,
    image: "../images/mobile7.webp",
  },
  {
    id: 25,
    category: "Flower",
    name: "White Lily",
    description: "Fresh White Lily Bouquet",
    price: 350,
    image: "../images/flower3.jpg",
  },
  {
    id: 26,
    category: "Laptop",
    name: "MSI Modern 15",
    description: "Intel i7 | 16GB RAM | 1TB SSD",
    price: 68999,
    image: "../images/laptop6.webp",
  },
  {
    id: 27,
    category: "Grocery",
    name: "Aashirvaad Atta",
    description: "Whole Wheat Flour 5kg",
    price: 320,
    image: "../images/grocery2.webp",
  },
  {
    id: 28,
    category: "Watch",
    name: "Noise ColorFit Pro",
    description: "Smart Watch with Heart Rate Monitor",
    price: 2999,
    image: "../images/watch2.jpg",
  },
  {
    id: 29,
    category: "Table",
    name: "Office Computer Table",
    description: "Wooden Computer Desk",
    price: 6499,
    image: "../images/table2.jpg",
  },
  {
    id: 30,
    category: "Pen",
    name: "Parker Vector",
    description: "Premium Ball Pen",
    price: 550,
    image: "../images/pen3.webp",
  },
  {
    id: 31,
    category: "Book",
    name: "Web Development",
    description: "HTML, CSS & JavaScript Guide",
    price: 899,
    image: "../images/book4.jpg",
  },
  {
    id: 32,
    category: "Vegetable",
    name: "Fresh Tomato",
    description: "Farm Fresh Tomato 1kg",
    price: 35,
    image: "../images/grocery3.jpg",
  },
  {
    id: 33,
    category: "Laptop",
    name: "ASUS VivoBook Pro",
    description: "Intel i7 | 16GB RAM | 1TB SSD",
    price: 119999,
    image: "../images/laptop7.webp",
  },
  {
    id: 34,
    category: "Flower",
    name: "Red Rose",
    description: "Fresh Rose Bouquet",
    price: 250,
    image: "../images/flower4.jpg",
  },
  {
    id: 35,
    category: "Mobile",
    name: "Nothing Phone 3",
    description: "12GB RAM | 256GB Storage",
    price: 54999,
    image: "../images/mobile8.jpg",
  },
  {
    id: 36,
    category: "Table",
    name: "Dining Table",
    description: "4 Seater Wooden Dining Table",
    price: 10999,
    image: "../images/table3.jpg",
  },
  {
    id: 37,
    category: "Pen",
    name: "Linc Glycer Pen",
    description: "Smooth Blue Ink Pen",
    price: 15,
    image: "../images/pen4.jpg",
  },
  {
    id: 38,
    category: "Grocery",
    name: "Fresh Carrot",
    description: "Fresh Carrot 1kg",
    price: 30,
    image: "../images/grocery4.jpg",
  },
  {
    id: 39,
    category: "Watch",
    name: "Boat Storm Smartwatch",
    description: "Bluetooth Calling Smart Watch",
    price: 2499,
    image: "../images/watch3.jpg",
  },
  {
    id: 40,
    category: "Book",
    name: "Web Development",
    description: "HTML, CSS & JavaScript Guide",
    price: 899,
    image: "../images/book5.webp",
  },
  {
    id: 41,
    category: "Laptop",
    name: "Lenovo ThinkPad E14",
    description: "Intel Core i5 | 16GB RAM | 512GB SSD",
    price: 67999,
    image: "../images/laptop8.jpg",
  },
  {
    id: 42,
    category: "Flower",
    name: "Pink Tulips",
    description: "Fresh Tulip Bouquet",
    price: 399,
    image: "../images/flower5.jpg",
  },
  {
    id: 43,
    category: "Grocery",
    name: "India Gate Basmati Rice",
    description: "Premium Basmati Rice 5kg",
    price: 699,
    image: "../images/grocery5.jpg",
  },
  {
    id: 44,
    category: "Watch",
    name: "Titan Neo Analog",
    description: "Men's Stainless Steel Watch",
    price: 4999,
    image: "../images/watch4.jpg",
  },
  {
    id: 45,
    category: "Vegetable",
    name: "Fresh Onion",
    description: "Organic Onion 1kg",
    price: 38,
    image: "../images/grocery6.jpg",
  },
  {
    id: 46,
    category: "Mobile",
    name: "Motorola Edge 60",
    description: "12GB RAM | 256GB Storage",
    price: 42999,
    image: "../images/mobile9.jpg",
  },
  {
    id: 47,
    category: "Pen",
    name: "Pilot V7 Roller Pen",
    description: "Smooth Roller Ball Pen",
    price: 75,
    image: "../images/pen5.jpg",
  },
  {
    id: 48,
    category: "Table",
    name: "Folding Study Table",
    description: "Portable Wooden Folding Table",
    price: 3299,
    image: "../images/table4.jpg",
  },
  {
    id: 49,
    category: "Laptop",
    name: "Apple MacBook Pro M4",
    description: "Apple M4 | 16GB RAM | 512GB SSD",
    price: 169999,
    image: "../images/laptop10.jpg",
  },
  {
    id: 50,
    category: "Flower",
    name: "White Orchid",
    description: "Premium Orchid Plant",
    price: 599,
    image: "../images/flower6.jpg",
  },
];

// add products to database if not already added
async function seedProducts() {
  try {
    var count = await Product.countDocuments();
    if (count == 0) {
      await Product.insertMany(productList);
      console.log("Products added to database");
    }
  } catch (err) {
    console.log(err);
  }
}

// get all products
async function getProducts(req, res) {
  try {
    var products = await Product.find({}, { _id: 0, __v: 0 });
    res.json(products);
  } catch (err) {
    console.log(err);
    res.status(500).json({ message: "Server error" });
  }
}

module.exports = { getProducts, seedProducts };
